version: '3'

services:
  app_nginx:
    build: ./infra/common/nginx
    volumes:
      - ./infra/common/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./infra/common/nginx/conf/conf.d:/etc/nginx/conf.d:delegated
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - app_php

  app_php:
    build: .
    working_dir: /app
    volumes:
      - ./codebase:/app:delegated
    env_file:
      - ./infra/local/.env.local
    environment:
      - APP_DB_HOST=app_mysql
      - APP_DB_PORT=3306
    depends_on:
      - app_mysql

  app_mysql:
    restart: unless-stopped
    build: ./infra/local/mysql
    volumes:
      - ./infra/local/mysql/data:/var/lib/mysql:delegated
      - ./infra/local/mysql/init:/init:delegated
    env_file:
      - ./infra/local/mysql/.env
      - ./infra/local/.env.local
    ports:
      - '33061:3306'
